
name: build node

on:
  push:
  workflow_dispatch:
    inputs:
      NODEVERSION:
        type: string
        default: '16.x'


jobs:
  build-node:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: capture default variables
        id: defaults
        run: |
          NODEVERSION=${{ inputs.nodeVersion }}
          echo "::set-output defaults=nodeVersion::${NODEVERSION:='16.x'}"

      - name: Use Node.js ${{ steps.defaults.outcome.nodeVersion }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.defaults.outcome.nodeVersion }}
      
      - name: npm install
        run: npm ci
      
      - name: display artifact
        run: ls -lsa
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!