
name: build node
env:
  NODEVERSION: '16.x'


on:
  push:
  workflow_call:
    inputs:
      NODEVERSION:
        type: string
        default: $NODEVERSION


jobs:
  build-node:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: capture default variables
        id: defaults
        run: |
          NODEVERSION=${{ inputs.nodeVersion }}
          VALUE=${NODEVERSION:='16.x'}
          echo "nodeVersion=${VALUE}" >> $GITHUB_OUTPUT
          echo $VALUE
          ls -lsa

      - name: Use Node.js ${{ steps.defaults.outputs.nodeVersion }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.defaults.outputs.nodeVersion }}
      
      - name: npm install
        run: |
          echo "the nodeVersion is ${{ steps.defaults.outputs.nodeVersion }}"
          cd node-example
          npm ci
          npm test
      
      - name: display artifact
        run: |
          cd node-example
          ls -lsa