name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      bicepTemplatePath:
        description: 'The path to the top-level bicep template, e.g. main.bicep'
        default: env/main.bicep
        type: string
      additionalBicepParameters:
        default: ''
        type: string
      clientAffix:
        required: true
        type: string
      env:
        default: Dv
        type: string
      resourceGroup:
        type: string
        required: true
      resourceGroupLocation:
        type: string
        default: 'eastus'
      vmImage:
        type: string
        default: 'ubuntu-latest'

jobs:
  build:
    runs-on: ${{ inputs.vmImage }}
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: echo "This is the default bicep template path -> ${{ inputs.bicepTemplatePath }}"
      - run: echo "These are additional bicep parameters -> ${{ inputs.additionalBicepParameters }}"
        shell: bash
      - run: Write-Host "This is the client affix -> ${{ inputs.clientAffix }}"
        shell: pwsh
      - run: Write-Host "This is the env -> ${{ inputs.env }}"
        shell: pwsh