name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      bicepTemplatePath:
        description: 'The path to the top-level bicep template, e.g. main.bicep'
        default: env/main.bicep
        type: string
      additionalBicepParameters:
        default: ''
        type: string
      clientAffix:
        required: true
        type: string
      env:
        default: Dv
        type: string
      resourceGroup:
        type: string
        required: true
      resourceGroupLocation:
        type: string
        default: 'eastus'
      variablesYamlPath:
        type: string
        default: './pipelines/variables.yaml'
      vmImage:
        type: string
        default: 'ubuntu-latest'

jobs:
  deploy:
    runs-on: ${{ inputs.vmImage }}
    defaults:
      run:
        shell: pwsh
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          # Credentials inherited from parent workflow
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Read YAML variables
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: yaml-data
        with:
          config: ${{ inputs.variablesYamlPath }}
      - run: |
          az account show
          az group create --name ${{ inputs.resourceGroup }} --location ${{ inputs.resourceGroupLocation }}
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
      # - run: |
      #     az --version
      #     az deployment group create `
      #       --resource-group ${{ inputs.resourceGroup }} `
      #       --name azuredeploy-${{ steps.current-time.outputs.time }} `
      #       --template-file ${{ inputs.bicepTemplatePath }} `
      #       --parameters `
      #         clientAffix="${{ steps.yaml-data.outputs['clientAffix'] }}" `
      #         projectAffix="${{ steps.yaml-data.outputs['projectAffix'] }}" `
      #         env="${{ steps.yaml-data.outputs['env'] }}" `
      #         ${{ inputs.additionalBicepParameters }}
      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          name: azuredeploy-${{ steps.current-time.outputs.time }}
          subscriptionId: ${{ steps.yaml-data.outputs['subscriptionId'] }}
          resourceGroupName: ${{ inputs.resourceGroup }}
          template: ${{ inputs.bicepTemplatePath }}
          failOnStdErr: false
          additionalArguments: |
            clientAffix=${{ steps.yaml-data.outputs['clientAffix'] }} \
            projectAffix=${{ steps.yaml-data.outputs['projectAffix'] }} \
            env=${{ steps.yaml-data.outputs['env'] }} \
            ${{ inputs.additionalBicepParameters }}